Repository wso2/product-apim, pull requests merged in 2018-09, with the labels that each got.

#3653 Update README versions to 2.6.0
  README.md
  README.txt
  modules/samples/MessageLogging/README.txt
  modules/samples/TwitterSearch/README.txt
  modules/samples/WikipediaAPI/README.txt
  modules/samples/YahooPlaceFinder/README.txt
  modules/samples/YoutubeFeeds/README.txt
  sample-scenarios/README.md
  sample-scenarios/sample10/README.md
  sample-scenarios/sample2/README.md
  sample-scenarios/sample4/README.md
  sample-scenarios/sample7/README.md
  sample-scenarios/sample8/README.md
  sample-scenarios/sample9/README.md
Labels: 2.6.0

#3690 Upgrade kernel version
  modules/distribution/resources/migration/wso2-api-migration-client/pom.xml
  modules/p2-profile/product/carbon.product
  pom.xml
Labels: 2.6.0-beta

#3698 Upgrade carbon.apimgt version
  pom.xml
Labels: 2.6.0

#3647 Integration tests for JWT generation with application type defined as JWT.
  modules/integration/tests-common/integration-test-utils/src/main/java/org/wso2/am/integration/test/utils/clients/APIStoreRestClient.java
  modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/token/TokenAPITestCase.java
Labels: 2.6.0

#3710 Modify readme with user-mgt.xml change
  modules/is-km/README.md
Labels: 2.6.0

#3711 Fix ChangeEndPointSecurityOfAPITestCase test case
  modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/am/integration/tests/api/lifecycle/ChangeEndPointSecurityOfAPITestCase.java
Labels: Docs/No Impact

#3712 Add Publisher Access Control feature related migrations
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/AccessControlMigrationClient.java
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/internal/APIMMigrationServiceComponent.java
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryService.java
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/250to260Migration/sql-scripts/postgresql.sql
Labels: Docs/Has Impact

#3715 Fix EmailUserNameLogin Test Case
  modules/integration/tests-integration/tests-backend/src/test/resources/artifacts/AM/configFiles/common/carbon.xml
  modules/integration/tests-integration/tests-backend/src/test/resources/artifacts/AM/configFiles/emailusernametest/carbon.xml
  modules/integration/tests-integration/tests-backend/src/test/resources/testng.xml
Labels: Docs/No Impact

#3717 Add migration db scripts for postgresql
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/250to260Migration/sql-scripts/postgresql.sql
  pom.xml
Labels: Docs/Has Impact

#3718 Add migration resources for 220 to 250 migration
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/220to250Migration/sql-scripts/db2.sql
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/220to250Migration/sql-scripts/h2.sql
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/220to250Migration/sql-scripts/mssql.sql
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/220to250Migration/sql-scripts/mysql.sql
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/220to250Migration/sql-scripts/oracle.sql
  modules/distribution/resources/migration/wso2-api-migration-client/src/main/resources/220to250Migration/sql-scripts/postgresql.sql
Labels: Docs/No Impact

#3720 Upgrade carbon-identity-framework and consent-management versions
  pom.xml
Labels: Docs/No Impact

#3722 Upgrade carbon.apimgt version
  pom.xml
Labels: 2.6.0

#3730 Upgrade carbon.apimgt version and fix old urls
  modules/styles/product/src/main/resources/META-INF/product.xml
  modules/styles/product/src/main/resources/web/product/about.html
  pom.xml
Labels: 2.6.0

#3733 Update about page in management console
  modules/styles/product/src/main/resources/web/product/about.html
Labels: 2.6.0, Docs/No Impact

#3734 Updating License.txt and allow skip test for integration tests
  LICENSE.txt
  modules/distribution/pom.xml
  modules/integration-tests/pom.xml
Labels: Docs/No Impact

#3740 Removing hard bound version from docker integration tests
  modules/distribution/docker/Dockerfile
  modules/distribution/pom.xml
  modules/integration-tests/pom.xml
  pom.xml
Labels: Docs/No Impact

#3741 Upgrate carbon-apimgt version
  pom.xml
Labels: Docs/No Impact

#3746 Update versions for the next development version
  modules/api-import-export/pom.xml
  modules/distribution/pom.xml
  modules/distribution/product/pom.xml
  modules/features/pom.xml
  modules/features/product/org.wso2.am.multitenancy.dashboard.ui.feature/pom.xml
  modules/features/product/org.wso2.am.styles.feature/pom.xml
  modules/features/product/pom.xml
  modules/integration/pom.xml
  modules/integration/tests-common/admin-clients/pom.xml
  modules/integration/tests-common/backend-service/jaxrs-app/pom.xml
  modules/integration/tests-common/backend-service/monitor-app/pom.xml
  modules/integration/tests-common/backend-service/pom.xml
  modules/integration/tests-common/framework-extensions/pom.xml
  modules/integration/tests-common/integration-test-extensions/pom.xml
  modules/integration/tests-common/integration-test-utils/pom.xml
  modules/integration/tests-common/pom.xml
  modules/integration/tests-common/ui-pages/pom.xml
  modules/integration/tests-integration/pom.xml
  modules/integration/tests-integration/tests-backend/pom.xml
  modules/oauth2-grant-types/pom.xml
  modules/org.wso2.am.multitenancy.dashboard.ui/pom.xml
  modules/p2-profile/pom.xml
  modules/p2-profile/product/pom.xml
  modules/styles/pom.xml
  modules/styles/product/pom.xml
  modules/styles/service/pom.xml
  pom.xml
  sample-scenarios/backend/pom.xml
  sample-scenarios/clients/admin/pom.xml
  sample-scenarios/clients/pom.xml
  sample-scenarios/clients/publisher/pom.xml
  sample-scenarios/clients/store/pom.xml
  sample-scenarios/pom.xml
  sample-scenarios/sample-utils/pom.xml
  sample-scenarios/sample1/pom.xml
  sample-scenarios/sample10/pom.xml
  sample-scenarios/sample2/pom.xml
  sample-scenarios/sample4/pom.xml
  sample-scenarios/sample7/pom.xml
  sample-scenarios/sample8/pom.xml
  sample-scenarios/sample9/pom.xml
Labels: Docs/No Impact

#3749 Add Authenticator Feature
  modules/distribution/pom.xml
  modules/integration-tests/src/main/java/org/wso2/carbon/apimgt/rest/integration/tests/util/TestUtil.java
  pom.xml
Labels: 3.0.0, Docs/No Impact

#3779 Upgrade carbon.apimgt version
  pom.xml
Labels: Docs/No Impact
